language: java
jdk: [oraclejdk8]
install: ant deps
script: ant testhalt
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
  - sudo apt-get install scons
  - sudo apt-get install zlib1g-dev
  - sudo apt-get install unzip
  - svn checkout http://svn.code.sf.net/p/nsis/code/ ~/nsis/
  - mkdir ~/nsis/
  - cd ~/nsis/
  - scons UNICODE=yes SKIPSTUBS=all SKIPPLUGINS=all SKIPUTILS=all SKIPMISC=all NSIS_CONFIG_CONST_DATA=no PREFIX=~/nsis/ install-compiler
  - mkdir share
  - ln -s ~/nsis share/nsis
  - wget -q https://www.free-decompiler.com/flash/nsis-3.0-stubs.zip
  - unzip nsis-3.0-stubs.zip -d Stubs
  - wget -q https://www.free-decompiler.com/flash/launch4j-3.9-linux.tgz
  - tar zxvf launch4j-3.9-linux.tgz -C ~ >/dev/null
  - cd -
  - echo "nsis.path = ~/nsis/bin/makensis" > tools.properties
  - echo "launch4j.path = ~/launch4j" >> tools.properties
